version: '3.4'

services:

  shorts_app:
    image: shorts-main:latest
    container_name: shorts_app
    ports:
      - 8000:8000
    env_file:
      - build/env
    volumes:
      - ./:/app/

  shorts_redis:
    image: redis:6.2.5-alpine
    container_name: shorts_redis

  influxdb:
    image: influxdb:1.8-alpine
    container_name: shorts_influxdb
    ports:
      - 8086:8086
    volumes:
      - ./volumes/influxdb:/var/lib/influxdb/
      - ./build/influxdb:/docker-entrypoint-initdb.d

  grafana:
    image: grafana/grafana:8.1.2
    container_name: shorts_grafana
    ports:
      - 3000:3000
    env_file:
      - build/env
    volumes:
      - ./volumes/grafana:/var/lib/grafana/
      - ./build/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./build/grafana/datasource.yml:/etc/grafana/provisioning/datasources/influxdb.yml
